# Generated by Django 3.0.8 on 2020-08-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielists',
            name='genres',
        ),
        migrations.AddField(
            model_name='movielists',
            name='genres',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Moviegenre',
        ),
    ]
