# Generated by Django 3.0.8 on 2020-08-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0002_auto_20200806_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielists',
            name='genres',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
