# Generated by Django 3.0.8 on 2020-08-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecollections',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moviecollections',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
