# Generated by Django 3.0.8 on 2020-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecollection', '0002_auto_20200806_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecollections',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
